---
########
# CURL #
########

# curl 7.58.0 and newer is required as of https://github.com/adoptium/temurin-build/issues/2751

- name: Check curl version
  shell: curl --version | head -n1 | awk '{print $2}'
  register: curl_version
  tags:
    - curl
    - skip_ansible_lint

- name: Print current version of Curl
  debug: var=curl_version.stdout
  tags: curl

- name: Set curl oldest variable
  set_fact:
    curl_oldest: 7.58.0
  tags: curl

- name: Set curl latest variable
  set_fact:
    curl_latest: 7.79.1
  tags: curl

- name: Download curl {{ curl_latest }}
  get_url:
    url: https://curl.se/download/curl-{{ curl_latest }}.tar.gz
    dest: /tmp/
    mode: 0440
    timeout: 25
    validate_certs: no
    checksum: sha256:370b11201349816287fb0ccc995e420277fbfcaf76206e309b3f60f0eda090c2
  retries: 3
  delay: 5
  register: curl_download
  until: curl_download is not failed
  when:
    - ansible_distribution != "MacOSX"
    - ((not curl_version.stdout) or ((curl_version.stdout) and (curl_version.stdout is version_compare(curl_oldest, operator='lt', strict=True))))
  tags: curl

- name: Extract curl
  unarchive:
    src: /tmp/curl-{{ curl_latest }}.tar.gz
    dest: /tmp/
    copy: False
  when:
    - ansible_distribution != "MacOSX"
    - ((not curl_version.stdout) or ((curl_version.stdout) and (curl_version.stdout is version_compare(curl_oldest, operator='lt', strict=True))))
  tags: curl

- name: Build and install curl {{ curl_latest }} in /usr/local
  shell: cd /tmp/curl-{{ curl_latest }} && ./configure --prefix=/usr/local/curl-{{ curl_latest }} && make && make install
  when:
    - ansible_distribution != "MacOSX"
    - ((not curl_version.stdout) or ((curl_version.stdout) and (curl_version.stdout is version_compare(curl_oldest, operator='lt', strict=True))))
  tags: curl

- name: Create /usr/local/bin/curl symlink
  file:
    src: /usr/local/curl-{{ curl_latest }}/bin/curl
    dest: /usr/local/bin/curl
    owner: root
    group: root
    state: link
  when:
    - ansible_distribution != "MacOSX"
    - ((not curl_version.stdout) or ((curl_version.stdout) and (curl_version.stdout is version_compare(curl_oldest, operator='lt', strict=True))))
  tags: curl

- name: Remove downloaded packages for curl {{ curl_latest }}
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/curl-{{ curl_latest }}.tar.gz
    - /tmp/curl-{{ curl_latest }}
  ignore_errors: yes
  when:
    - ansible_distribution != "MacOSX"
    - ((not curl_version.stdout) or ((curl_version.stdout) and (curl_version.stdout is version_compare(curl_oldest, operator='lt', strict=True))))
  tags: curl

- name: Install curl version {{ curl_latest }}+ for MacOS
  homebrew:
    name: curl
    state: latest
  when:
    - ansible_distribution == "MacOSX"
    - ((not curl_version.stdout) or ((curl_version.stdout) and (curl_version.stdout is version_compare(curl_oldest, operator='lt', strict=True))))
  tags: curl

- name: Create /usr/local/bin/curl symlink
  file:
    src: /usr/local/Cellar/curl/{{ curl_latest }}/bin/curl
    dest: /usr/local/bin/curl
    owner: administrator
    group: admin
    state: link
  when:
    - ansible_distribution == "MacOSX"
    - ((not curl_version.stdout) or ((curl_version.stdout) and (curl_version.stdout is version_compare(curl_oldest, operator='lt', strict=True))))
  tags: curl
