---
##########################
# adoptopenjdk_variables #
##########################

# Domain for setting hostname
Domain: adoptopenjdk.net

# Sudoers file
Sudoers_File: /etc/sudoers

# Jenkins User Variables:
Jenkins_Username: jenkins

# Superuser Variables:
Superuser_Account: Enabled

# Nagios Variables:
Nagios_Plugins: Enabled
Nagios_Monitoring: Enabled
Nagios_Master_IP: 78.47.239.96

# Security Variables:
Security: Enabled

# JCK Variables:
jckftp_Username: jckftp

# Vendor Variables:
Vendor_File: Disabled
Vendor_Playbook: /Vendor_Files/Vendor_Playbook/Vendor.yml

# Default BootJDK installed
bootjdk: hotspot

# GPG Public Keys
key:
  curl: 27EDEAF22F3ABCEB50DB9A125CC908FDB71E12C2 # Daniel Stenberg <daniel@haxx.se>
  apache: CE8075A251547BEE249BC151A2115AE15F6B8B72 # Stefan Bodewig <bodewig@apache.org>
  autoconf: A7A16B4A2527436A # Eric Blake <eblake@redhat.com>
  