---
- name: Add Docker Repo for SLES12
  command: zypper ar https://download.docker.com/linux/sles/docker-ce.repo

- name: Install Docker on SLES12
  zypper:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  when:
    - ansible_architecture == "x86_64"
  tags:
    # TODO: Package installs should not use latest
    - skip_ansible_lint
