---
###############################
# Adoptium - Ansible Playbook #
###############################

- name: Dockernode playbook
  hosts: all
  gather_facts: yes

  roles:
    - role: Debug
      tags: debug
    - role: Get_Vendor_Files
      tags: deploy
    - role: deploy_container
      tags: deploy
