---
# Xcode 11.7 is needed to build x64 JDK8 om Arm64 Mac
# Xcode11.7 can be downloaded from https://developer.apple.com/download/all after authentication with apple ID and password
# See https://github.com/adoptium/infrastructure/issues/2536#issuecomment-1708716478
# The Xcode11.7 package should be present in /Vendor_Files/mac/Xcode_11.7.xip on the controller node

- name: Check if Xcode11.7 is installed
  stat:
    path: /Applications/Xcode-11.7.app/
  register: xcode11_installed

- name: Install Xcode11.7
  when: not xcode11_installed.stat.exists
  block:
    - name: Transfer Xcode11.7 over to remote machine
      copy:
        src: /Vendor_Files/mac/Xcode_11.7.xip
        dest: /tmp/Xcode_11.7.xip

    - name: Extract Xcode11.7
      shell: cd /tmp/ && xip -x /tmp/Xcode_11.7.xip

    - name: Move Xcode11.7 to /Applications directory
      copy:
        src: /tmp/Xcode.app
        dest: /Applications/Xcode-11.7.app/
        remote_src: true

    - name: Clean up Xcode11.7.xip file
      file:
        path: /tmp/Xcode_11.7.xip
        state: absent
