---

# Download and install GnuPG2-2.30-2 from https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/RPMS/ppc/gnupg2/

- name: Check if GnuPG2 is already installed
  stat:
    path: /usr/bin/gpg
  register: gpg

- name: Download and install GnuPG2 from aixtoolbox
  when: gpg.stat.islnk is not defined
  block:

    - name: Download GnuPG2
      get_url:
        url: https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/RPMS/ppc/gnupg2/gnupg2-2.0.30-2.aix6.1.ppc.rpm
        dest: /tmp/gnupg2-2.0.30-2.aix6.1.ppc.rpm
        mode: 0440
        timeout: 25
        checksum: sha256:6a590b71b1b4177d2c998065f3caf982134058aa0939a2dea26079d4020a51c2

    - name: Yum install GnuPG2
      command: yum -y install /tmp/gnupg2-2.0.30-2.aix6.1.ppc.rpm

    - name: Link /usr/bin/gpg2 to /usr/bin/gpg
      file:
        src: /usr/bin/gpg2
        dest: /usr/bin/gpg
        state: link
