name: Build QEMU

on:
  pull_request:
    paths:
    - .github/workflows/build_qemu.yml
    - ansible/playbooks/AdoptOpenJDK_Unix_Playbook/**
    branches:         
    - master

permissions:
  contents: read

jobs:
  build_job:
    # The host should always be linux
    runs-on: ubuntu-18.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu18.04
          - arch: aarch64
            distro: buster
          - arch: ppc64le
            distro: ubuntu18.04
          - arch: s390x
            distro: ubuntu18.04
          - arch: armv7
            distro: jessie

    steps:
      - uses: actions/checkout@v2.1.0

      - name: Run on architecture
        uses: uraimo/run-on-arch-action@v2.3.0
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
      
      - name: Install Ansible
        run: |
          apt -y update
          apt -y install ansible

      - name: Run the UNIX playbook
        run: |
          echo "localhost ansible_user=runner ansible_connection=local" > ansible/hosts
          set -eux
          cd ansible
          sudo ansible-playbook -i hosts --extra-vars 'git_sha=${{ github.sha }}' playbooks/AdoptOpenJDK_Unix_Playbook/main.yml --skip-tags="adoptopenjdk,jenkins"
